"""USSD menu state identifiers. The main menu mirrors the web farmer navigation:
Farm (Shamba) · Ghala · Market (Soko) · Finance (Fedha)."""

MAIN_MENU = "MAIN_MENU"
UNREGISTERED = "UNREGISTERED"

REGISTRATION_NAME = "REGISTRATION_NAME"
REGISTRATION_LOCATION = "REGISTRATION_LOCATION"
REGISTRATION_SIZE = "REGISTRATION_SIZE"
REGISTRATION_CROP = "REGISTRATION_CROP"
REGISTRATION_CROP_ACRES = "REGISTRATION_CROP_ACRES"

FARM_MENU = "FARM_MENU"
FARM_ADD_CROP = "FARM_ADD_CROP"
FARM_ADD_CROP_ACRES = "FARM_ADD_CROP_ACRES"

GHALA_MENU = "GHALA_MENU"

MARKET_MENU = "MARKET_MENU"

FINANCE_MENU = "FINANCE_MENU"
FINANCE_PROFILE = "FINANCE_PROFILE"

LOANS_MENU = "LOANS_MENU"
LOAN_AMOUNT = "LOAN_AMOUNT"
LOAN_PURPOSE = "LOAN_PURPOSE"
LOAN_PIN = "LOAN_PIN"

SAVINGS_MENU = "SAVINGS_MENU"
SAVINGS_DEPOSIT_GOAL = "SAVINGS_DEPOSIT_GOAL"
SAVINGS_DEPOSIT_AMOUNT = "SAVINGS_DEPOSIT_AMOUNT"
SAVINGS_NEW_BUCKET = "SAVINGS_NEW_BUCKET"
SAVINGS_NEW_TARGET = "SAVINGS_NEW_TARGET"

INSURANCE_MENU = "INSURANCE_MENU"
DISASTER_TYPE = "DISASTER_TYPE"
DISASTER_CONFIRM = "DISASTER_CONFIRM"
INSURANCE_REQUEST = "INSURANCE_REQUEST"
INSURANCE_PIN = "INSURANCE_PIN"
